apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      cloud.google.com/neg: '{"exposed_ports": {"9000":{"name": "cn-ksakasai-ingress-app-9000"}}}'
    labels:
      app: istio-ingressgateway
      install.operator.istio.io/owning-resource: installed-state
      install.operator.istio.io/owning-resource-namespace: istio-system
      istio: ingressgateway
      istio.io/rev: default
      operator.istio.io/component: IngressGateways
      operator.istio.io/managed: Reconcile
      operator.istio.io/version: 1.19.1
      release: istio
    name: istio-ingressgateway
    namespace: istio-system
  spec:
    clusterIP: 10.112.10.169
    clusterIPs:
    - 10.112.10.169
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: status-port
      port: 15021
    - name: http2
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
    - name: cn-ksakasai-app
      port: 9000
      targetPort: 9000
    selector:
      app: istio-ingressgateway
      istio: ingressgateway
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      cloud.google.com/neg: '{"ingress":true}'
    labels:
      app: istiod
      install.operator.istio.io/owning-resource: installed-state
      install.operator.istio.io/owning-resource-namespace: istio-system
      istio: pilot
      istio.io/rev: default
      operator.istio.io/component: Pilot
      operator.istio.io/managed: Reconcile
      operator.istio.io/version: 1.19.1
      release: istio
    name: istiod
    namespace: istio-system
  spec:
    clusterIP: 10.112.5.64
    clusterIPs:
    - 10.112.5.64
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: grpc-xds
      port: 15010
    - name: https-dns
      port: 15012
    - name: https-webhook
      port: 443
      targetPort: 15017
    - name: http-monitoring
      port: 15014
    selector:
      app: istiod
      istio: pilot
kind: List
metadata:
  resourceVersion: ""
