apiVersion: v1
items:
- apiVersion: networking.istio.io/v1beta1
  kind: Gateway
  metadata:
    name: work-gke-gce-gateway
    namespace: work-gke-gce
  spec:
    selector:
      istio: ingressgateway
    servers:
    - hosts:
      - "*"
      port:
        name: cn-ksakasai-app
        number: 9000
        protocol: HTTP
kind: List
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
    name: work-gke-gce-destination-rule
    namespace: work-gke-gce
spec:
  host: server-clusterip.work-gke-gce.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---      
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: work-gke-gce-virtual-service
  namespace: work-gke-gce
spec:
  gateways:
  - work-gke-gce-gateway
  hosts:
  -  "*"
  http:
  - route:
    - destination:
        host: server-clusterip
        port:
          number: 8080